apiVersion: v1
kind: Service
metadata:
  name: cicd-website
  namespace: cicd-namespace
  labels:
    app: cicd-website
spec:
  type: LoadBalancer
  selector:
    app: cicd-website
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-website-nodeport
  namespace: cicd-namespace
  labels:
    app: cicd-website
spec:
  type: NodePort
  selector:
    app: cicd-website
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080
    protocol: TCP
